version: '2'
services:
  postgres:
    image: postgres:9.6.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my-password
  wildfly:
    image: tonda100/wildfly-postgresql
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_NAME=tech11-task
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - postgres